name: 'If Branch Merged'
description: 'A GitHub action to check if a pull request head branch has been merged to another branch'
author: 'Gavin.Guohao.Wu'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
