name: 'If Branch Merged'
description: 'A GitHub action to check if a pull request head branch has been merged to another branch'
author: 'Gavin.Guohao.Wu'
inputs:
  expected: # change this
    required: true
    description: 'Input the name or regex of the branch which the merge is expected'
runs:
  using: 'node12'
  main: 'dist/index.js'
